# Generated by Django 4.1.1 on 2022-10-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_admin', '0002_remove_profile_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hashcode',
            field=models.CharField(max_length=254),
        ),
    ]
