# Generated by Django 4.1.1 on 2022-09-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_admin', '0002_rename_supervision_graduate_supervision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='end_date',
            new_name='completion_date',
        ),
        migrations.AddField(
            model_name='student',
            name='current_role',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='funding_sources',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='taships',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='thesis_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_funding_awarded',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
