# Generated by Django 4.1.1 on 2022-09-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp_admin', '0002_reminder_setup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reminder_Setup',
            new_name='Setup_Reminder',
        ),
    ]
