# Generated by Django 4.1.1 on 2022-09-13 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp_admin', '0004_rename_setup_reminder_reminder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam_Reminder',
            new_name='Reminder_Inbox',
        ),
    ]
