# Generated by Django 4.1.1 on 2022-09-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp_admin', '0004_rename_reminder_inbox_sent_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='month',
            new_name='months',
        ),
    ]
