# Generated by Django 4.1.1 on 2022-10-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_admin', '0004_alter_student_email_alter_student_loa_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
