# Generated by Django 4.1.1 on 2022-09-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_admin', '0005_rename_exam_reminder_reminder_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_graduate_advisor',
            field=models.BooleanField(default=False),
        ),
    ]
