# Generated by Django 4.1.1 on 2022-09-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_admin', '0006_remove_sent_reminder_comp_exam_sent_reminder_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sent_reminder',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.AddField(
            model_name='student',
            name='comprehensive_exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
