# Generated by Django 4.1.1 on 2022-11-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_admin', '0006_alter_student_hashcode_alter_student_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sis_created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sis_updated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
