# Generated by Django 4.1.1 on 2022-09-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_admin', '0007_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='program',
        ),
        migrations.AddField(
            model_name='professor',
            name='program',
            field=models.ManyToManyField(to='gp_admin.program'),
        ),
    ]
