# Generated by Django 4.1.1 on 2022-09-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_admin', '0007_alter_sent_reminder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=150),
        ),
    ]
