# Generated by Django 4.1.1 on 2022-09-15 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp_admin', '0008_remove_professor_program_professor_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='program',
            new_name='programs',
        ),
    ]
